# Generated by Django 4.2.6 on 2023-10-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_app', '0002_alter_book_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
