# Generated by Django 4.2.6 on 2023-10-19 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_app', '0004_userprofile_last_saved_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='last_saved_description',
        ),
    ]
