# Generated by Django 4.2.6 on 2023-10-21 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_app', '0006_userprofile_friends_alter_friendship_friend_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='current_book',
            new_name='currently_reading_book',
        ),
    ]
