# Generated by Django 4.2.6 on 2023-10-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_app', '0007_rename_current_book_userprofile_currently_reading_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='user_rating',
            field=models.IntegerField(default=0),
        ),
    ]
