# Generated by Django 4.2.6 on 2023-10-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_app', '0011_alter_book_user_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='user_rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
