# Generated by Django 4.2.6 on 2023-10-25 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_app', '0015_book_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='liked',
        ),
    ]
