# Generated by Django 4.2.6 on 2023-10-31 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_app', '0022_alter_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
    ]
