# Generated by Django 4.2.6 on 2023-11-07 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_app', '0025_userprofile_email_userprofile_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
